version: "3.7"

name: enem

networks:
  web:

services:
  enem_db:
    image: postgres:latest
    restart: always
    networks:
      - web
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Erik2202*
      POSTGRES_DB: enem
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
  enem_server:
    build: .
    container_name: enem_server
    ports:
      - "8050:8050"
    depends_on:
      - enem_db
    networks:
      - web
    restart: always
