version: "3.7"

name: enem

networks:
  web:
    external: true

services:
  enem_web:
    build: ../web
    container_name: enem_web
    restart: always
    depends_on:
      - enem_server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.enem.rule=Host(`enem.erikna.com`)"
      - "traefik.http.routers.enem.entrypoints=web, websecure"
      - "traefik.http.routers.enem.tls=true"
      - "traefik.http.routers.enem.tls.certresolver=production"
    networks:
      - web
  enem_server:
    build: .
    container_name: enem_server    
    labels:
      - traefik.enable=true
      - traefik.http.routers.nest.rule=Host(`enemapi.erikna.com`)
      - traefik.http.routers.nest.entrypoints=web, websecure
      - traefik.http.routers.nest.tls=true
      - traefik.http.services.nest.loadbalancer.server.port=8050
      - traefik.http.routers.nest.tls.certresolver=production
    networks:
      - web
    restart: always
