CREATE TABLE users(
	id VARCHAR(36) NOT NULL,
	fullName VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	questions JSON NOT NULL);

CREATE TABLE question(
	id VARCHAR(36) NOT NULL,
	url VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	answers JSON NOT NULL,
	rightAnswer VARCHAR(255) NOT NULL,
	description LONGTEXT(65535) NOT NULL,
	ask LONGTEXT(65535) NOT NULL);
