CREATE TABLE users (
  id UUID PRIMARY KEY,
  fullname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  questions JSONB NOT NULL
);

CREATE TABLE question (
  id UUID PRIMARY KEY,
  url VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  answers JSONB NOT NULL,
  rightanswer VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  ask TEXT NOT NULL
);
